name: GitHub to Feishu

on:
  schedule:
    - cron: '*/10 * * * *'  # æ¯ 10 åˆ†é’Ÿè¿è¡Œä¸€æ¬¡
  workflow_dispatch:  # æ‰‹åŠ¨è§¦å‘

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      env:
        GITHUB_USERNAME: ${{ secrets.GIT_USERNAME }}
        FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
      run: |
        python - <<EOF
        import requests
        import json
        import os

        GITHUB_USERNAME = os.getenv('GITHUB_USERNAME')
        FEISHU_WEBHOOK_URL = os.getenv('FEISHU_WEBHOOK_URL')

        def get_github_events(username):
            url = f'https://api.github.com/users/{username}/events'
            response = requests.get(url)
            events = response.json()
            return events

        def send_to_feishu(text):
            headers = {
                'Content-Type': 'application/json'
            }
            data = {
                "msg_type": "text",
                "content": {
                    "text": text
                }
            }
            response = requests.post(FEISHU_WEBHOOK_URL, headers=headers, data=json.dumps(data))
            return response.json()

        def process_event(event):
            event_type = event.get('type')
            repo_name = event['repo']['name']
            actor = event['actor']['login']

            if event_type == 'WatchEvent':
                return f"ğŸ“ˆ {actor} starred the repository {repo_name}"
            
            elif event_type == 'ForkEvent':
                return f"ğŸ´ {actor} forked the repository {repo_name}"
            
            elif event_type == 'PushEvent':
                commits = event['payload']['commits']
                commit_messages = [commit['message'] for commit in commits]
                return f"ğŸ·ï¸ {actor} pushed commits to {repo_name}:\n" + '\n'.join(commit_messages)
            
            elif event_type == 'CreateEvent':
                ref_type = event['payload']['ref_type']
                ref = event['payload']['ref']
                return f"âš¡ {actor} created a {ref_type} {ref} in {repo_name}"
            
            else:
                return None

        events = get_github_events(GITHUB_USERNAME)

        for event in events:
            message = process_event(event)
            if message:
                send_to_feishu(message)
        EOF
